version: "3.7"
services:

  # PostgreSQL database
  postgres:
    image: postgres:latest
    container_name: mlflow-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflowdb
  
    ports:
      - 6432:5432
    networks:
      - mlflowNetwork
      - shared_reverse_proxy_net

    volumes:
      - ./postgres-data:/var/lib/postgresql
    restart: unless-stopped 

  # MinIO server (S3-kompatibler Artefakt-Speicher)
  minio:
    image: minio/minio
    container_name: mlflow-minio
    env_file:
      - ./mlflow.env
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER=${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - mlflowNetwork
      -
   
    volumes: 
      - ./minio-data:/data 
    healthcheck:
      
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # Service zum Erstellen des MinIO-Buckets
  minio-create-bucket:
    image: minio/mc
    container_name: mlflow-create-bucket
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - mlflowNetwork
      - shared_reverse_proxy_net
    # Entrypoint zum Erstellen des "bucket"
    entrypoint: >
      /bin/bash -c "
      mc alias set minio http://minio:9000 minio_user minio_password &&
      if ! mc ls minio/bucket/ >/dev/null 2>&1; then
        echo 'Erstelle bucket...'
        mc mb minio/bucket
      else
        echo 'bucket existiert bereits'
      fi
      "

  # MLflow Tracking Server
  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: mlflow-server

    env_file:
      - ./mlflow.env
    
    ports:
      - "7500:7500"
    
    environment:
      # Tracking Store (Postgres intern: postgres:5432)
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      # MinIO Endpoint (S3 Kompatibilit√§t)
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL} # <-- Jetzt mit Bindestrich
      # MinIO Zugangsdaten
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # Standard-Artefakt-Speicherort
      - MLFLOW_S3_ARTIFACT_ROOT=${MLFLOW_S3_ARTIFACT_ROOT}

    command: >
      mlflow server
      --host 0.0.0.0
      --port 7500
      --backend-store-uri ${MLFLOW_TRACKING_URI}
      --default-artifact-root ${MLFLOW_S3_ARTIFACT_ROOT}
      
    networks:
      - mlflowNetwork
      - shared_reverse_proxy_net
    
    depends_on:
      postgres:
        condition: service_started
      minio-create-bucket:
        condition: service_completed_successfully
        
    restart: unless-stopped


networks:
  mlflowNetwork:
    driver: bridge
  shared_reverse_proxy_net:
    external: true
volumes:
  postgres_data:
    driver: local